# Generated by Django 2.2.11 on 2020-03-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0002_rateinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
