# Generated by Django 2.2.11 on 2020-03-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0003_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Taught_by',
        ),
        migrations.AddField(
            model_name='module',
            name='Taught_by',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
